### ISSUE TITLE
Select Color Scheme for App

### ISSUE THREAD

**Issue by FroeMic** [FroeMic/FullStack_Info_HW07#18]
**Note:** *Just add the result to our nuclino workspace. Since you don't change the code base, no feature branch is needed for this one.*

Select a color scheme for your app. #makeAllTheThingsBeautiful

Plz consider the following categories:

<img width="697" alt="Bootstrap Color Categories" src="https://user-images.githubusercontent.com/15179255/37259696-d26a61d4-2546-11e8-82bf-be77b7eccb65.png">

**Comment by Rabberina** [comment]
Some personal favs for our project, ranked in order of preference. Let me know what you think & feel free to add:

https://www.canva.com/learn/website-color-schemes/

#37. Cool Jewel Tones
#15. Splash of Color
#31. Cool and Calm

**Comment by FroeMic** [comment]
@Rabberina *Cool Jewel Tones* look good I think. This is what it would look like. If you approve we can add it to our project.

<img width="887" alt="screen shot 2018-03-12 at 10 56 56" src="https://user-images.githubusercontent.com/15179255/37301484-ea594810-25e5-11e8-8b57-60a11199f0e6.png">

**Comment by Rabberina** [comment]
Of course, if it's your fav too! 

Happy birthday

**Comment by FroeMic** [comment]
Perfect, then let's practice the *git-flow* 😎 

Can you create a feature branch where you add the css file with the updated color scheme and link it in the `base.html` instead of the normal `now-ui-kit.css` file? Then commit and push the changes and create a pull request.

**Now UI Kit CSS file with Cool-Jewel-Tones color scheme:**
https://www.dropbox.com/s/dtwc0zi1tolx1w1/now-ui-kit-cool-jewel-tones.css?dl=0
