### ISSUE TITLE
03 Create Trip

### ISSUE THREAD

**Issue by FroeMic** [FroeMic/FullStack_Info_HW07#3]
As a *TripLeader*
I can *create a new trip (Name, Destination)*
so that *I can share my awesome travel plans*

**Comment by Rabberina** [comment]
1. Create a button on the Trips page
2. Create the route: /trips/create
3. Create a Trip form where users input trip info
4. Code the HTML to show the form
5. Validate user input; if input is valid, add trip to database
6. Redirect user to the ShowTrip page at /trips/< id >

**Comment by FroeMic** [comment]
Implemented in  53a7b47
